#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/9c2e6a44-37eb-45af-9d66-631d9f9ef6dc

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSchedule wakeuptime;
  bool wecker_AN;
  CloudTime vorlaufZeit;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  pinMode(LED_BUILTIN, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  digitalWrite(LED_BUILTIN, HIGH);
  delay(500);
  digitalWrite(LED_BUILTIN, LOW);
}

void loop() {
  ArduinoCloud.update();
  // Your code here


}



/*
  Since Wakeuptime is READ_WRITE variable, onWakeuptimeChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWakeuptimeChange()  {
  // Add your code here to act upon Wakeuptime change

  digitalWrite(LED_BUILTIN, HIGH);
  delay(500);
  digitalWrite(LED_BUILTIN, LOW);
}

/*
  Since VorlaufZeit is READ_WRITE variable, onVorlaufZeitChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVorlaufZeitChange()  {
  // Add your code here to act upon VorlaufZeit change
  digitalWrite(LED_BUILTIN, HIGH);
  delay(200);
  digitalWrite(LED_BUILTIN, LOW);
}

/*
  Since WeckerAN is READ_WRITE variable, onWeckerANChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWeckerANChange()  {
  // Add your code here to act upon WeckerAN change
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  digitalWrite(LED_BUILTIN, LOW);
}