// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2d77336e-d75a-4f47-9e3a-5579f0a45028";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onWakeuptimeChange();
void onWeckerANChange();
void onVorlaufZeitChange();

CloudSchedule wakeuptime;
bool wecker_AN;
CloudTime vorlaufZeit;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(wakeuptime, READWRITE, ON_CHANGE, onWakeuptimeChange);
  ArduinoCloud.addProperty(wecker_AN, READWRITE, ON_CHANGE, onWeckerANChange);
  ArduinoCloud.addProperty(vorlaufZeit, READWRITE, ON_CHANGE, onVorlaufZeitChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
